project_name: openlab
gitdeploy_version: "1.0.4"
type: "static"

application_dir: "{{ deploy_dir }}"

# Configs below will not usually change
deploy_dir: "{{ install_root }}/{{ project_name }}"
project_repo: "git@github.com:NUKnightLab/openlab.knightlab.com.git"
static_service: "s3"
static_dir: "{{ application_dir }}/dist"
static_dest: "s3://{{ static_bucket }}" # static hosted site goes in root of bucket
static_prep: "cp ./deploy/env.{{ env }} ./.env; npm install --only=production --no-bin-links; npm run compile"

# Configs common to all projects
application_user: apps
install_root: /home/{{ application_user }}/sites
virtualenv_root: /home/{{ application_user }}/env

# environment keys must match deployment branch names. Value is the name
# of the branch to be merged into this environment during deployment.
supported_envs:
  stg: master
  prd: stg
